# CONFIGURATION PYTHON FILE

# GENERAL SETTINGS
MAPSIZE_X = 1600
MAPSIZE_Y = 1200

SCREENSIZE_X = 800
SCREENSIZE_Y = 600
HALF_SCREENSIZE_X = int(SCREENSIZE_X/2)
HALF_SCREENSIZE_Y = int(SCREENSIZE_Y/2)

FPS = 30

CAMERASLACK = 90 

# GAME SETTINGS
MOVERATE = 10

STARTSIZE = 50
EATSIZE = STARTSIZE - 15
WINSIZE = 300

GAMEOVERTIME = 4

NUMENEMIES = 30
ENEMYMINSIZE = 10
MINSPEED = 3
MAXSPEED = 8
DIRCHANGEFREQ = 3 # % chance of direction change per frame

# CONSTANTS
LEFT = 'left'
RIGHT = 'right'

# COLOUR CONSTANTS
WHITE = (255, 255, 255)
BLACK = (  0,   0,   0)

RED   = (255,   0,   0)
GREEN = (  0, 255,   0)
BLUE  = (  0,   0, 255)

BALLCOLOUR = [RED, GREEN, BLUE]




